[build]
  command = "pnpm install && pnpm build"
  functions = "netlify/functions"
  publish = ".next"

[context.production]
  command = "pnpm install && pnpm build"

[context.deploy-preview]
  command = "pnpm install && pnpm build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
