[build]
  command = "pnpm install && pnpm build"
  publish = "out"

[context.production]
  command = "pnpm install && pnpm build"

[context.deploy-preview]
  command = "pnpm install && pnpm build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
